### ISSUE TITLE
AlderLake and RaptorLake Platforms define EnableItbm in two locations

### ISSUE THREAD

**Issue by marcjones-syspro** [slimbootloader/slimbootloader#2324]
On AlderLake and RaptorLake Platforms,  `EnableItbm` is defined in[ CfgData_Power.yaml](https://github.com/slimbootloader/slimbootloader/blob/b86a51ce98c09772d44cc398cb4cdab0442f7e88/Platform/AlderlakeBoardPkg/CfgData/CfgData_Power.yaml#L674) and [CfgData_Silicon.yaml](https://github.com/slimbootloader/slimbootloader/blob/b86a51ce98c09772d44cc398cb4cdab0442f7e88/Platform/AlderlakeBoardPkg/CfgData/CfgData_Silicon.yaml#L47) and they have opposite defaults. One is enabled and the other isn't. 

CfgData_Power .yaml:
```yaml
  - EnableItbm   :
      name         : Intel Turbo Boost Max Technology 3.0
      type         : Combo
      option       : $EN_DIS
      help         : >
                     Intel Turbo Boost Max Technology 3.0. 0- Disabled; <b>1- Enabled</b>
      length       : 0x01
      value        : 0x01
```

cfgData_Silicon.yaml:
```yaml
  - EnableItbm   :
      condition    : $(COND_S0IX_DIS)
      name         : Intel Turbo Boost Max Technology 3.0
      type         : Combo
      option       : $EN_DIS
      help         : >
                     Intel Turbo Boost Max Technology 3.0. 0- Disabled; <b>1- Enabled</b>
      length       : 0x01
      value        : 0x00
```

A number of .DLT files set [SILICON_CFG_DATA.EnableItbm | 0x1](https://github.com/slimbootloader/slimbootloader/blob/b86a51ce98c09772d44cc398cb4cdab0442f7e88/Platform/AlderlakeBoardPkg/CfgData/CfgDataInt_Adln_Crb_Ddr5.dlt#L122) so you would assume that setting it to 0 would work,
but FspsUpdUpdateLib.c uses [PowerCfgData-->EnableItbm](https://github.com/slimbootloader/slimbootloader/blob/b86a51ce98c09772d44cc398cb4cdab0442f7e88/Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c#L815) and also has some other logic if [S0IX is enabled](https://github.com/slimbootloader/slimbootloader/blob/b86a51ce98c09772d44cc398cb4cdab0442f7e88/Platform/AlderlakeBoardPkg/Library/FspsUpdUpdateLib/FspsUpdUpdateLib.c#L761) 

I don't think that this is working as intended.
